apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: reticula-backend
  labels:
    app: reticula
    tier: backend
spec:
  replicas: 7
  selector:
    matchLabels:
      app: reticula
      tier: backend
  template:
    metadata:
      labels:
        app: reticula
        tier: backend
    spec:
      containers:
      - image: emilioemmanuel05/reticula:latest
        name: reticulanet
        ports: 
          - containerPort: 8001
            hostPort: 8002
        volumeMounts:
          - name: reticula-persistent
            mountPath: /var/lib/net
      volumes:
        - name: reticula-persistent
          persistentVolumeClaim:
            claimName: reticula-volume-claim
