apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: reticula-backend
  labels:
    app: reticula
    tier: backend
spec:
  replicas: 7
  selector:
    matchLabels:
      app: reticula
      tier: backend
  template:
    metadata:
      labels:
        app: reticula
        tier: backend
    spec:
      containers:
      - name: reticula-net
        image: emilioemmanuel05/reticula:latest
        ports: 
          - containerPort: 8001
            hostPort: 8001
